# Taskfile for SPICE build orchestration
# https://taskfile.dev
#
# All building, compiling, testing, and running is done inside containers

version: '3'

silent: false

vars:
  CONTAINER_BIN: docker
  CONTAINER_FILE: Containerfile
  CONTAINER_CONTEXT: .
  CONTAINER_IMAGE: spice-builder
  CONTAINER_TAG: latest
  CONTAINER_NAME: spice-api
  CONTAINER_NAME_TEST: spice-api-test
  COMPOSE_SERVICE: spice-api
  SERVICE_HOST_PORT: 50000
  SERVICE_PORT: 50000
  API_BASE: http://localhost:{{.SERVICE_HOST_PORT}}/api/spice/sgp4
  # Remote image settings
  REMOTE_REGISTRY: ghcr.io/haisamido
  REMOTE_IMAGE: spice
  REMOTE_TAG: latest
  PLATFORM: linux/amd64

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  container:build:
    desc: Build the container image locally (WASM + npm + TypeScript)
    cmds:
      - "{{.CONTAINER_BIN}} compose build {{.COMPOSE_SERVICE}}"

  container:pull:
    desc: Pull remote container image from registry
    cmds:
      - "{{.CONTAINER_BIN}} pull --platform {{.PLATFORM}} {{.REMOTE_REGISTRY}}/{{.REMOTE_IMAGE}}:{{.REMOTE_TAG}}"
      - "{{.CONTAINER_BIN}} tag {{.REMOTE_REGISTRY}}/{{.REMOTE_IMAGE}}:{{.REMOTE_TAG}} {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}}"
      - echo "Pulled and tagged as {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}}"

  container:test:
    desc: Run tests inside container
    deps:
      - container:build
    cmds:
      - "{{.CONTAINER_BIN}} run --rm {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} npm test"

  container:example:
    desc: Run the Node.js example inside container
    deps:
      - container:build
    cmds:
      - "{{.CONTAINER_BIN}} run --rm {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} node examples/node-example.js"

  container:start:
    desc: Build and start the REST API server (detached)
    cmds:
      - "GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo '-') {{.CONTAINER_BIN}} compose up -d --build"
      - echo "Waiting for server to start..."
      - sleep 3
      - echo ""
      - echo "Server running at http://localhost:{{.SERVICE_HOST_PORT}}"
      - echo "  task container:logs         - View logs"
      - echo "  task container:logs:follow  - Follow logs"
      - echo "  task container:stop         - Stop server"

  container:start:pull:
    desc: Pull remote image and start the REST API server (detached)
    deps:
      - container:pull
    cmds:
      - "GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo '-') {{.CONTAINER_BIN}} compose up -d"
      - echo "Waiting for server to start..."
      - sleep 3
      - echo ""
      - echo "Server running at http://localhost:{{.SERVICE_HOST_PORT}}"
      - echo "  task container:logs         - View logs"
      - echo "  task container:logs:follow  - Follow logs"
      - echo "  task container:stop         - Stop server"

  container:stop:
    desc: Stop and remove the REST API server container
    cmds:
      - "{{.CONTAINER_BIN}} compose down -v"

  container:restart:
    desc: Stop and restart the REST API server
    cmds:
      - task: container:stop
      - task: container:start

  container:logs:
    desc: View logs from the running REST API server
    cmds:
      - "{{.CONTAINER_BIN}} compose logs {{.COMPOSE_SERVICE}} {{.CLI_ARGS}}"

  container:logs:follow:
    desc: Follow logs from the running REST API server
    cmds:
      - "{{.CONTAINER_BIN}} compose logs -f {{.COMPOSE_SERVICE}}"

  container:shell:
    desc: Open a shell in the container build environment
    deps:
      - container:build
    cmds:
      - "{{.CONTAINER_BIN}} run --rm -it {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} bash"

  # ==========================================================================
  # API Test Tasks
  # ==========================================================================

  test:api:health:
    desc: Test health endpoint
    cmds:
      - echo "=== Testing Health Endpoint ==="
      - curl -s {{.API_BASE}}/health | jq .

  test:api:parse:tle:
    desc: Test TLE parse endpoint
    cmds:
      - echo "=== Testing TLE Parse Endpoint ==="
      - |
        curl -s -X POST {{.API_BASE}}/parse \
          -H "Content-Type: application/json" \
          -d '{
            "line1": "1 25544U 98067A   24015.50000000  .00016717  00000-0  10270-3 0  9025",
            "line2": "2 25544  51.6400 208.9163 0006703  30.0825 330.0579 15.49560830    19"
          }' | jq .

  test:api:propagate:tle:
    desc: Test TLE propagate endpoint (single time)
    cmds:
      - echo "=== Testing TLE Propagate Endpoint (single time) ==="
      - |
        curl -s -X POST "{{.API_BASE}}/propagate?t0=2024-01-15T12:00:00" \
          -H "Content-Type: application/json" \
          -d '{
            "line1": "1 25544U 98067A   24015.50000000  .00016717  00000-0  10270-3 0  9025",
            "line2": "2 25544  51.6400 208.9163 0006703  30.0825 330.0579 15.49560830    19"
          }' | jq .

  test:api:propagate:range:
    desc: Test TLE propagate (2 hours, 60-sec step)
    cmds:
      - echo "=== Testing TLE Propagate (2 hours, 60-sec step) ==="
      - |
        curl -s -X POST "{{.API_BASE}}/propagate?t0=2024-01-15T12:00:00&tf=2024-01-15T14:00:00&step=60&unit=sec" \
          -H "Content-Type: application/json" \
          -d '{
            "line1": "1 25544U 98067A   24015.50000000  .00016717  00000-0  10270-3 0  9025",
            "line2": "2 25544  51.6400 208.9163 0006703  30.0825 330.0579 15.49560830    19"
          }' | jq .

  test:api:utc-to-et:
    desc: Test UTC to ET conversion endpoint
    cmds:
      - echo "=== Testing UTC to ET Conversion ==="
      - curl -s "{{.API_BASE}}/time/utc-to-et?utc=2024-01-15T12:00:00" | jq .

  test:api:et-to-utc:
    desc: Test ET to UTC conversion endpoint
    cmds:
      - echo "=== Testing ET to UTC Conversion ==="
      - curl -s "{{.API_BASE}}/time/et-to-utc?et=758894469.184" | jq .

  test:api:models:
    desc: Test models list endpoint
    cmds:
      - echo "=== Testing Models List ==="
      - curl -s http://localhost:{{.SERVICE_HOST_PORT}}/api/models/ | jq .

  test:api:models:wgs72:
    desc: Test WGS-72 model details
    cmds:
      - echo "=== Testing WGS-72 Model ==="
      - curl -s http://localhost:{{.SERVICE_HOST_PORT}}/api/models/wgs/wgs72 | jq .

  test:api:models:wgs84:
    desc: Test WGS-84 model details
    cmds:
      - echo "=== Testing WGS-84 Model ==="
      - curl -s http://localhost:{{.SERVICE_HOST_PORT}}/api/models/wgs/wgs84 | jq .

  test:api:propagate:wgs84:
    desc: Test propagate with WGS-84 model
    cmds:
      - echo "=== Testing Propagate with WGS-84 ==="
      - |
        curl -s -X POST "{{.API_BASE}}/propagate?t0=2024-01-15T12:00:00&wgs=wgs84" \
          -H "Content-Type: application/json" \
          -d '{
            "line1": "1 25544U 98067A   24015.50000000  .00016717  00000-0  10270-3 0  9025",
            "line2": "2 25544  51.6400 208.9163 0006703  30.0825 330.0579 15.49560830    19"
          }' | jq .

  test:api:parse:omm:
    desc: Test OMM parse endpoint
    cmds:
      - echo "=== Testing OMM Parse Endpoint ==="
      - |
        curl -s -X POST {{.API_BASE}}/omm/parse \
          -H "Content-Type: application/json" \
          -d '{
            "OBJECT_NAME": "ISS (ZARYA)",
            "OBJECT_ID": "1998-067A",
            "EPOCH": "2024-01-15T12:00:00.000",
            "MEAN_MOTION": 15.49560830,
            "ECCENTRICITY": 0.0006703,
            "INCLINATION": 51.6400,
            "RA_OF_ASC_NODE": 208.9163,
            "ARG_OF_PERICENTER": 30.0825,
            "MEAN_ANOMALY": 330.0579,
            "NORAD_CAT_ID": 25544,
            "BSTAR": 0.00010270,
            "MEAN_MOTION_DOT": 0.00016717
          }' | jq .

  test:api:propagate:omm:
    desc: Test OMM propagate endpoint (via unified endpoint)
    cmds:
      - echo "=== Testing OMM Propagate (unified endpoint) ==="
      - |
        curl -s -X POST "{{.API_BASE}}/propagate?t0=2024-01-15T12:00:00&tf=2024-01-15T14:00:00&step=60&unit=sec&input_type=omm" \
          -H "Content-Type: application/json" \
          -d '{
            "omm": {
              "OBJECT_NAME": "ISS (ZARYA)",
              "OBJECT_ID": "1998-067A",
              "EPOCH": "2024-01-15T12:00:00.000",
              "MEAN_MOTION": 15.49560830,
              "ECCENTRICITY": 0.0006703,
              "INCLINATION": 51.6400,
              "RA_OF_ASC_NODE": 208.9163,
              "ARG_OF_PERICENTER": 30.0825,
              "MEAN_ANOMALY": 330.0579,
              "NORAD_CAT_ID": 25544,
              "BSTAR": 0.00010270,
              "MEAN_MOTION_DOT": 0.00016717
            }
          }' | jq .

  test:api:omm:to-tle:
    desc: Test OMM to TLE conversion
    cmds:
      - echo "=== Testing OMM to TLE Conversion ==="
      - |
        curl -s -X POST {{.API_BASE}}/omm/to-tle \
          -H "Content-Type: application/json" \
          -d '{
            "OBJECT_NAME": "ISS (ZARYA)",
            "OBJECT_ID": "1998-067A",
            "EPOCH": "2024-01-15T12:00:00.000",
            "MEAN_MOTION": 15.49560830,
            "ECCENTRICITY": 0.0006703,
            "INCLINATION": 51.6400,
            "RA_OF_ASC_NODE": 208.9163,
            "ARG_OF_PERICENTER": 30.0825,
            "MEAN_ANOMALY": 330.0579,
            "NORAD_CAT_ID": 25544,
            "BSTAR": 0.00010270,
            "MEAN_MOTION_DOT": 0.00016717
          }' | jq .

  test:api:tle:to-omm:
    desc: Test TLE to OMM conversion
    cmds:
      - echo "=== Testing TLE to OMM Conversion ==="
      - |
        curl -s -X POST {{.API_BASE}}/tle/to-omm \
          -H "Content-Type: application/json" \
          -d '{
            "line1": "1 25544U 98067A   24015.50000000  .00016717  00000-0  10270-3 0  9025",
            "line2": "2 25544  51.6400 208.9163 0006703  30.0825 330.0579 15.49560830    19",
            "name": "ISS (ZARYA)"
          }' | jq .

  test:api:all:
    desc: Run all API tests (server must be running)
    cmds:
      - task: test:api:health
      - task: test:api:parse:tle
      - task: test:api:propagate:tle
      - task: test:api:propagate:range
      - task: test:api:utc-to-et
      - task: test:api:et-to-utc
      - task: test:api:models
      - task: test:api:models:wgs72
      - task: test:api:models:wgs84
      - task: test:api:propagate:wgs84
      - task: test:api:parse:omm
      - task: test:api:propagate:omm
      - task: test:api:omm:to-tle
      - task: test:api:tle:to-omm

  container:test:api:
    desc: Start server, run all API tests, then stop
    cmds:
      - task: container:start
      - task: test:api:all
      - task: container:stop

  # ==========================================================================
  # Cleanup Tasks
  # ==========================================================================

  container:rmi:
    desc: Remove the container image
    cmds:
      - "{{.CONTAINER_BIN}} rmi {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} || true"

  container:expunge:
    desc: Stop all containers and remove all images related to this repo
    deps:
      - container:stop
    cmds:
      - |
        echo "Stopping containers..."
        {{.CONTAINER_BIN}} stop {{.CONTAINER_NAME}} {{.CONTAINER_NAME_TEST}} 2>/dev/null || true

        echo "Removing containers and volumes..."
        {{.CONTAINER_BIN}} rm -v {{.CONTAINER_NAME}} {{.CONTAINER_NAME_TEST}} 2>/dev/null || true

        echo "Removing image {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}}..."
        {{.CONTAINER_BIN}} rmi {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} 2>/dev/null || true

        echo "Pruning dangling images, volumes, and networks..."
        {{.CONTAINER_BIN}} image prune -f
        {{.CONTAINER_BIN}} volume prune -f
        {{.CONTAINER_BIN}} network prune -f

        echo "Done."
