# Taskfile for SPICE build orchestration
# https://taskfile.dev
#
# All building, compiling, testing, and running is done inside Docker

version: '3'

silent: false

vars:
  CONTAINER_BIN: docker
  CONTAINER_FILE: Dockerfile
  CONTAINER_CONTEXT: .
  CONTAINER_IMAGE: spice-builder
  CONTAINER_TAG: latest
  CONTAINER_NAME: spice-api
  CONTAINER_NAME_TEST: spice-api-test
  COMPOSE_SERVICE: spice-api
  SERVICE_HOST_PORT: 50000
  SERVICE_PORT: 50000
  API_BASE: http://localhost:{{.SERVICE_HOST_PORT}}/api/spice/sgp4

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  docker:build:
    desc: Build the Docker image (WASM + npm + TypeScript)
    cmds:
      - "{{.CONTAINER_BIN}} compose build {{.COMPOSE_SERVICE}}"

  docker:test:
    desc: Run tests inside Docker
    deps:
      - docker:build
    cmds:
      - "{{.CONTAINER_BIN}} run --rm {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} npm test"

  docker:example:
    desc: Run the Node.js example inside Docker
    deps:
      - docker:build
    cmds:
      - "{{.CONTAINER_BIN}} run --rm {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} node examples/node-example.js"

  docker:start:
    desc: Build and start the REST API server (detached)
    cmds:
      - "{{.CONTAINER_BIN}} compose up -d --build"
      - echo "Waiting for server to start..."
      - sleep 3
      - echo ""
      - echo "Server running at http://localhost:{{.SERVICE_HOST_PORT}}"
      - echo "  task docker:logs         - View logs"
      - echo "  task docker:logs:follow  - Follow logs"
      - echo "  task docker:stop         - Stop server"

  docker:stop:
    desc: Stop and remove the REST API server container
    cmds:
      - "{{.CONTAINER_BIN}} compose down -v"

  docker:logs:
    desc: View logs from the running REST API server
    cmds:
      - "{{.CONTAINER_BIN}} compose logs {{.COMPOSE_SERVICE}} {{.CLI_ARGS}}"

  docker:logs:follow:
    desc: Follow logs from the running REST API server
    cmds:
      - "{{.CONTAINER_BIN}} compose logs -f {{.COMPOSE_SERVICE}}"

  docker:shell:
    desc: Open a shell in the Docker build environment
    deps:
      - docker:build
    cmds:
      - "{{.CONTAINER_BIN}} run --rm -it {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} bash"

  # ==========================================================================
  # API Test Tasks
  # ==========================================================================

  test:api:health:
    desc: Test health endpoint
    cmds:
      - echo "=== Testing Health Endpoint ==="
      - curl -s {{.API_BASE}}/health | jq .

  test:api:parse:
    desc: Test TLE parse endpoint
    cmds:
      - echo "=== Testing Parse Endpoint ==="
      - |
        curl -s -X POST {{.API_BASE}}/parse \
          -H "Content-Type: application/json" \
          -d '{
            "line1": "1 25544U 98067A   24015.50000000  .00016717  00000-0  10270-3 0  9025",
            "line2": "2 25544  51.6400 208.9163 0006703  30.0825 330.0579 15.49560830    19"
          }' | jq .

  test:api:propagate:
    desc: Test TLE propagate endpoint
    cmds:
      - echo "=== Testing Propagate Endpoint ==="
      - |
        curl -s -X POST {{.API_BASE}}/propagate \
          -H "Content-Type: application/json" \
          -d '{
            "line1": "1 25544U 98067A   24015.50000000  .00016717  00000-0  10270-3 0  9025",
            "line2": "2 25544  51.6400 208.9163 0006703  30.0825 330.0579 15.49560830    19",
            "time": "2024-01-15T12:00:00"
          }' | jq .

  test:api:utc-to-et:
    desc: Test UTC to ET conversion endpoint
    cmds:
      - echo "=== Testing UTC to ET Conversion ==="
      - curl -s "{{.API_BASE}}/time/utc-to-et?utc=2024-01-15T12:00:00" | jq .

  test:api:et-to-utc:
    desc: Test ET to UTC conversion endpoint
    cmds:
      - echo "=== Testing ET to UTC Conversion ==="
      - curl -s "{{.API_BASE}}/time/et-to-utc?et=758894469.184" | jq .

  test:api:models:
    desc: Test models list endpoint
    cmds:
      - echo "=== Testing Models List ==="
      - curl -s http://localhost:{{.SERVICE_HOST_PORT}}/api/models/ | jq .

  test:api:models:wgs72:
    desc: Test WGS-72 model details
    cmds:
      - echo "=== Testing WGS-72 Model ==="
      - curl -s http://localhost:{{.SERVICE_HOST_PORT}}/api/models/wgs/wgs72 | jq .

  test:api:models:wgs84:
    desc: Test WGS-84 model details
    cmds:
      - echo "=== Testing WGS-84 Model ==="
      - curl -s http://localhost:{{.SERVICE_HOST_PORT}}/api/models/wgs/wgs84 | jq .

  test:api:propagate:wgs84:
    desc: Test propagate with WGS-84 model
    cmds:
      - echo "=== Testing Propagate with WGS-84 ==="
      - |
        curl -s -X POST "{{.API_BASE}}/propagate?model=wgs84" \
          -H "Content-Type: application/json" \
          -d '{
            "line1": "1 25544U 98067A   24015.50000000  .00016717  00000-0  10270-3 0  9025",
            "line2": "2 25544  51.6400 208.9163 0006703  30.0825 330.0579 15.49560830    19",
            "time": "2024-01-15T12:00:00"
          }' | jq .

  test:api:all:
    desc: Run all API tests (server must be running)
    cmds:
      - task: test:api:health
      - task: test:api:parse
      - task: test:api:propagate
      - task: test:api:utc-to-et
      - task: test:api:et-to-utc
      - task: test:api:models
      - task: test:api:models:wgs72
      - task: test:api:models:wgs84
      - task: test:api:propagate:wgs84

  docker:test:api:
    desc: Start server, run all API tests, then stop
    cmds:
      - task: docker:start
      - task: test:api:all
      - task: docker:stop

  # ==========================================================================
  # Cleanup Tasks
  # ==========================================================================

  docker:rmi:
    desc: Remove the Docker image
    cmds:
      - "{{.CONTAINER_BIN}} rmi {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} || true"

  docker:expunge:
    desc: Stop all containers and remove all images related to this repo
    deps:
      - docker:stop
    cmds:
      - |
        echo "Stopping containers..."
        {{.CONTAINER_BIN}} stop {{.CONTAINER_NAME}} {{.CONTAINER_NAME_TEST}} 2>/dev/null || true

        echo "Removing containers and volumes..."
        {{.CONTAINER_BIN}} rm -v {{.CONTAINER_NAME}} {{.CONTAINER_NAME_TEST}} 2>/dev/null || true

        echo "Removing image {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}}..."
        {{.CONTAINER_BIN}} rmi {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} 2>/dev/null || true

        echo "Pruning dangling images, volumes, and networks..."
        {{.CONTAINER_BIN}} image prune -f
        {{.CONTAINER_BIN}} volume prune -f
        {{.CONTAINER_BIN}} network prune -f

        echo "Done."
