# Taskfile for SPICE build orchestration
# https://taskfile.dev
#
# All building, compiling, testing, and running is done inside containers

version: '3'

silent: false

includes:
  test:
    taskfile: ./tests/Taskfile.yaml
    vars:
      SERVICE_HOST_PORT: '{{.SERVICE_HOST_PORT}}'

vars:
  CONTAINER_BIN: docker
  CONTAINER_FILE: Containerfile
  CONTAINER_CONTEXT: .
  COMPOSE_FILE: compose.yaml

  CONTAINER_IMAGE: spice-builder
  CONTAINER_TAG: latest
  CONTAINER_NAME: spice-api
  CONTAINER_NAME_TEST: spice-api-test

  CONTAINER_HOST: localhost
  COMPOSE_SERVICE: spice-api

  SERVICE_HOST_PORT: 50000
  SERVICE_PORT: 50000
  
  BASE: http://{{.CONTAINER_HOST}}:{{.SERVICE_HOST_PORT}}
  UI_BASE: http://{{.CONTAINER_HOST}}:{{.SERVICE_HOST_PORT}}/ui
  API_BASE: http://{{.CONTAINER_HOST}}:{{.SERVICE_HOST_PORT}}/api/spice/sgp4

  # Remote image settings
  REMOTE_REGISTRY: ghcr.io/haisamido
  REMOTE_IMAGE: spice
  REMOTE_TAG: latest
  PLATFORM: linux/amd64

  SGP4_POOL_SIZE: 12

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  container:build:
    desc: Build the container image locally (WASM + npm + TypeScript)
    cmds:
      - "{{.CONTAINER_BIN}} compose -f {{.COMPOSE_FILE}} build {{.COMPOSE_SERVICE}}"

  container:pull:
    desc: Pull remote container image from registry
    cmds:
      - "{{.CONTAINER_BIN}} pull --platform {{.PLATFORM}} {{.REMOTE_REGISTRY}}/{{.REMOTE_IMAGE}}:{{.REMOTE_TAG}}"
      - "{{.CONTAINER_BIN}} tag {{.REMOTE_REGISTRY}}/{{.REMOTE_IMAGE}}:{{.REMOTE_TAG}} {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}}"
      - echo "Pulled and tagged as {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}}"

  container:test:
    desc: Run tests inside container (results written to ./tests/<test>/results/)
    deps:
      - container:build
    cmds:
      - "{{.CONTAINER_BIN}} run --rm -e MODE=test -v {{.PWD}}/tests:/app/tests {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} npm test"
    vars:
      PWD:
        sh: pwd

  container:example:
    desc: Run the Node.js example inside container
    deps:
      - container:build
    cmds:
      - "{{.CONTAINER_BIN}} run --rm {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} node examples/node-example.js"

  container:start:
    desc: "START HERE: Build and start the REST API server (detached)"
    cmds:
      - "GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo '-') {{.CONTAINER_BIN}} compose -f {{.COMPOSE_FILE}} up -d --build"
      - echo "Waiting for server to start..."
      - sleep 3
      - echo ""
      - echo "Server running at http://localhost:{{.SERVICE_HOST_PORT}}"
      - echo "  task container:logs         - View logs"
      - echo "  task container:logs:follow  - Follow logs"
      - echo "  task container:stop         - Stop server"

  container:run:
    desc: Alias for container:start
    cmds:
      - task: container:start

  container:up:
    desc: Alias for container:start
    cmds:
      - task: container:start

  container:start:pull:
    desc: Pull remote image and start the REST API server (detached)
    deps:
      - container:pull
    cmds:
      - "GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo '-') {{.CONTAINER_BIN}} compose -f {{.COMPOSE_FILE}} up -d"
      - echo "Waiting for server to start..."
      - sleep 3
      - echo ""
      - echo "Server running at http://localhost:{{.SERVICE_HOST_PORT}}"
      - echo "  task container:logs         - View logs"
      - echo "  task container:logs:follow  - Follow logs"
      - echo "  task container:stop         - Stop server"

  container:stop:
    desc: Stop and remove the REST API server container
    cmds:
      - "{{.CONTAINER_BIN}} compose -f {{.COMPOSE_FILE}} down -v"

  container:down:
    desc: Alias for container:stop
    cmds:
      - task: container:stop

  container:restart:
    desc: Stop and restart the REST API server
    cmds:
      - task: container:stop
      - task: container:start

  container:logs:
    desc: View logs from the running REST API server
    cmds:
      - "{{.CONTAINER_BIN}} compose -f {{.COMPOSE_FILE}} logs {{.COMPOSE_SERVICE}} {{.CLI_ARGS}}"

  container:logs:follow:
    desc: Follow logs from the running REST API server
    cmds:
      - "{{.CONTAINER_BIN}} compose -f {{.COMPOSE_FILE}} logs -f {{.COMPOSE_SERVICE}}"

  container:shell:
    desc: Open a shell in the container build environment
    deps:
      - container:build
    cmds:
      - "{{.CONTAINER_BIN}} run --rm -it {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} bash"

  container:test:api:
    desc: Start server, run all API tests, then stop
    cmds:
      - task: container:start
      - task: test:api:all
      - task: container:stop

  # ==========================================================================
  # Cleanup Tasks
  # ==========================================================================

  container:rmi:
    desc: Remove the container image
    cmds:
      - "{{.CONTAINER_BIN}} rmi {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} || true"

  container:expunge:
    desc: Stop all containers and remove all images related to this repo
    deps:
      - container:stop
    cmds:
      - |
        echo "Stopping containers..."
        {{.CONTAINER_BIN}} stop {{.CONTAINER_NAME}} {{.CONTAINER_NAME_TEST}} 2>/dev/null || true

        echo "Removing containers and volumes..."
        {{.CONTAINER_BIN}} rm -v {{.CONTAINER_NAME}} {{.CONTAINER_NAME_TEST}} 2>/dev/null || true

        echo "Removing image {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}}..."
        {{.CONTAINER_BIN}} rmi {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} 2>/dev/null || true

        echo "Pruning dangling images, volumes, and networks..."
        {{.CONTAINER_BIN}} image prune -f
        {{.CONTAINER_BIN}} volume prune -f
        {{.CONTAINER_BIN}} network prune -f

        echo "Done."
