# Taskfile for SPICE build orchestration
# https://taskfile.dev
#
# All building, compiling, testing, and running is done inside containers

version: '3'

silent: false

includes:
  test:
    taskfile: ./tests/Taskfile.yaml
    vars:
      SERVICE_HOST_PORT: '{{.SERVICE_HOST_PORT}}'

vars:
  CONTAINER_BIN: docker
  CONTAINER_FILE: Containerfile
  CONTAINER_CONTEXT: .
  COMPOSE_FILE: compose.yaml

  CONTAINER_IMAGE: spice-builder
  CONTAINER_TAG: latest
  CONTAINER_NAME: spice-api
  CONTAINER_NAME_TEST: spice-api-test

  CONTAINER_HOST: localhost
  COMPOSE_SERVICE: spice-api

  SERVICE_HOST_PORT: 50000
  SERVICE_PORT: 50000
  
  BASE: http://{{.CONTAINER_HOST}}:{{.SERVICE_HOST_PORT}}
  UI_BASE: http://{{.CONTAINER_HOST}}:{{.SERVICE_HOST_PORT}}/ui
  API_BASE: http://{{.CONTAINER_HOST}}:{{.SERVICE_HOST_PORT}}/api/spice/sgp4

  # Remote image settings
  REMOTE_REGISTRY: ghcr.io/haisamido
  REMOTE_IMAGE: spice
  REMOTE_TAG: latest
  PLATFORM: linux/amd64

  SGP4_POOL_SIZE: 12

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  container:build:
    desc: Build the container image locally (WASM + npm + TypeScript)
    cmds:
      - "{{.CONTAINER_BIN}} compose -f {{.COMPOSE_FILE}} build {{.COMPOSE_SERVICE}}"

  container:pull:
    desc: Pull remote container image from registry
    cmds:
      - "{{.CONTAINER_BIN}} pull --platform {{.PLATFORM}} {{.REMOTE_REGISTRY}}/{{.REMOTE_IMAGE}}:{{.REMOTE_TAG}}"
      - "{{.CONTAINER_BIN}} tag {{.REMOTE_REGISTRY}}/{{.REMOTE_IMAGE}}:{{.REMOTE_TAG}} {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}}"
      - echo "Pulled and tagged as {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}}"

  container:test:
    desc: Run tests inside container (results written to ./tests/<test>/results/)
    deps:
      - container:build
    cmds:
      - "{{.CONTAINER_BIN}} run --rm -e MODE=test -v {{.PWD}}/tests:/app/tests {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} npm test"
    vars:
      PWD:
        sh: pwd

  container:example:
    desc: Run the Node.js example inside container
    deps:
      - container:build
    cmds:
      - "{{.CONTAINER_BIN}} run --rm {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} node examples/node-example.js"

  container:start:
    desc: "START HERE: Build and start the REST API server (detached)"
    cmds:
      - "GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo '-') {{.CONTAINER_BIN}} compose -f {{.COMPOSE_FILE}} up -d --build"
      - echo "Waiting for server to start..."
      - sleep 3
      - echo ""
      - echo "Server running at http://localhost:{{.SERVICE_HOST_PORT}}"
      - echo "  task container:logs         - View logs"
      - echo "  task container:logs:follow  - Follow logs"
      - echo "  task container:stop         - Stop server"

  container:run:
    desc: Alias for container:start
    cmds:
      - task: container:start

  container:up:
    desc: Alias for container:start
    cmds:
      - task: container:start

  container:start:pull:
    desc: Pull remote image and start the REST API server (detached)
    deps:
      - container:pull
    cmds:
      - "GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo '-') {{.CONTAINER_BIN}} compose -f {{.COMPOSE_FILE}} up -d"
      - echo "Waiting for server to start..."
      - sleep 3
      - echo ""
      - echo "Server running at http://localhost:{{.SERVICE_HOST_PORT}}"
      - echo "  task container:logs         - View logs"
      - echo "  task container:logs:follow  - Follow logs"
      - echo "  task container:stop         - Stop server"

  container:stop:
    desc: Stop and remove the REST API server container
    cmds:
      - "{{.CONTAINER_BIN}} compose -f {{.COMPOSE_FILE}} down -v"

  container:down:
    desc: Alias for container:stop
    cmds:
      - task: container:stop

  container:restart:
    desc: Stop and restart the REST API server
    cmds:
      - task: container:stop
      - task: container:start

  container:logs:
    desc: View logs from the running REST API server
    cmds:
      - "{{.CONTAINER_BIN}} compose -f {{.COMPOSE_FILE}} logs {{.COMPOSE_SERVICE}} {{.CLI_ARGS}}"

  container:logs:follow:
    desc: Follow logs from the running REST API server
    cmds:
      - "{{.CONTAINER_BIN}} compose -f {{.COMPOSE_FILE}} logs -f {{.COMPOSE_SERVICE}}"

  container:shell:
    desc: Open a shell in the container build environment
    deps:
      - container:build
    cmds:
      - "{{.CONTAINER_BIN}} run --rm -it {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} bash"

  container:benchmark:
    desc: Run SGP4 WASM benchmark (no HTTP overhead). Args SATS=9534 STEP=60
    deps:
      - container:build
    vars:
      SATS: '{{.SATS | default "9534"}}'
      STEP: '{{.STEP | default "60"}}'
    cmds:
      - "{{.CONTAINER_BIN}} run --rm {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} npx tsx lib/benchmark.ts {{.SATS}} {{.STEP}}"

  # ==========================================================================
  # Native (Host) Tasks - Run directly on host machine, not in Docker
  # ==========================================================================

  native:setup:
    desc: Download and extract CSPICE toolkit for native compilation
    vars:
      CSPICE_DIR: '{{.PWD}}/.cspice'
      KERNELS_DIR: '{{.PWD}}/.cspice/kernels'
      PWD:
        sh: pwd
    cmds:
      - cmd: |
          if [ -d "{{.CSPICE_DIR}}/cspice" ]; then
            echo "CSPICE already installed at {{.CSPICE_DIR}}/cspice"
            exit 0
          fi

          echo "Detecting platform..."
          ARCH=$(uname -m)
          OS=$(uname -s)

          if [ "$OS" = "Darwin" ]; then
            if [ "$ARCH" = "arm64" ]; then
              URL="https://naif.jpl.nasa.gov/pub/naif/toolkit/C/MacM1_OSX_clang_64bit/packages/cspice.tar.Z"
            else
              URL="https://naif.jpl.nasa.gov/pub/naif/toolkit/C/MacIntel_OSX_AppleC_64bit/packages/cspice.tar.Z"
            fi
          elif [ "$OS" = "Linux" ]; then
            URL="https://naif.jpl.nasa.gov/pub/naif/toolkit/C/PC_Linux_GCC_64bit/packages/cspice.tar.Z"
          else
            echo "Unsupported OS: $OS"
            exit 1
          fi

          echo "Downloading CSPICE from $URL..."
          mkdir -p "{{.CSPICE_DIR}}"
          curl -sL -o "{{.CSPICE_DIR}}/cspice.tar.Z" "$URL"

          echo "Extracting..."
          cd "{{.CSPICE_DIR}}" && tar -xzf cspice.tar.Z && rm cspice.tar.Z

          echo "Downloading leapseconds kernel..."
          mkdir -p "{{.KERNELS_DIR}}"
          curl -sL -o "{{.KERNELS_DIR}}/naif0012.tls" \
            https://naif.jpl.nasa.gov/pub/naif/generic_kernels/lsk/naif0012.tls

          echo "CSPICE installed at {{.CSPICE_DIR}}/cspice"
    status:
      - test -d "{{.PWD}}/.cspice/cspice"

  native:build:
    desc: Compile the native SGP4 benchmark
    deps:
      - native:setup
    vars:
      CSPICE_DIR: '{{.PWD}}/.cspice/cspice'
      PWD:
        sh: pwd
    cmds:
      - cmd: |
          mkdir -p bin
          echo "Compiling native benchmark..."
          cc -O3 -o bin/benchmark_native src/benchmark_native.c \
            -I{{.CSPICE_DIR}}/include \
            {{.CSPICE_DIR}}/lib/cspice.a -lm
          echo "Built: bin/benchmark_native"

  native:benchmark:
    desc: Run SGP4 native benchmark (compiled on host). Args SATS=9534 STEP=60
    deps:
      - native:build
    vars:
      SATS: '{{.SATS | default "9534"}}'
      STEP: '{{.STEP | default "60"}}'
      KERNELS_DIR: '{{.PWD}}/.cspice/kernels'
      PWD:
        sh: pwd
    cmds:
      - bin/benchmark_native {{.SATS}} {{.STEP}}
    env:
      SPICE_KERNELS: '{{.KERNELS_DIR}}'

  native:build:parallel:
    desc: Compile the multi-process native SGP4 benchmark
    deps:
      - native:setup
    vars:
      CSPICE_DIR: '{{.PWD}}/.cspice/cspice'
      PWD:
        sh: pwd
    cmds:
      - cmd: |
          mkdir -p bin
          echo "Compiling multi-process native benchmark..."
          cc -O3 -o bin/benchmark_native_mp src/benchmark_native_mp.c \
            -I{{.CSPICE_DIR}}/include \
            {{.CSPICE_DIR}}/lib/cspice.a -lm
          echo "Built: bin/benchmark_native_mp"

  native:benchmark:parallel:
    desc: Run parallel SGP4 native benchmark (fork). Args SATS=9534 STEP=60 WORKERS=4
    deps:
      - native:build:parallel
    vars:
      SATS: '{{.SATS | default "9534"}}'
      STEP: '{{.STEP | default "60"}}'
      WORKERS: '{{.WORKERS | default "12"}}'
      KERNELS_DIR: '{{.PWD}}/.cspice/kernels'
      PWD:
        sh: pwd
    cmds:
      - bin/benchmark_native_mp {{.SATS}} {{.STEP}} {{.WORKERS}}
    env:
      SPICE_KERNELS: '{{.KERNELS_DIR}}'

  native:benchmark:optimal:
    desc: Find optimal WORKERS count for parallel benchmark. Args SATS=9534 STEP=60 MAX_WORKERS=16
    deps:
      - native:build:parallel
    vars:
      SATS: '{{.SATS | default "9534"}}'
      STEP: '{{.STEP | default "60"}}'
      MAX_WORKERS: '{{.MAX_WORKERS | default "16"}}'
      KERNELS_DIR: '{{.PWD}}/.cspice/kernels'
      PWD:
        sh: pwd
    env:
      SPICE_KERNELS: '{{.KERNELS_DIR}}'
    cmds:
      - cmd: |
          echo "Finding optimal WORKERS for native:benchmark:parallel"
          echo "  SATS: {{.SATS}}"
          echo "  STEP: {{.STEP}}"
          echo "  Testing WORKERS: 1 to {{.MAX_WORKERS}}"
          echo ""
          echo "WORKERS | Throughput (prop/s) | Wall Time (s) | Speedup"
          echo "--------|--------------------:|---------------:|--------:"

          BASELINE=0
          BEST_WORKERS=1
          BEST_THROUGHPUT=0

          for W in $(seq 1 {{.MAX_WORKERS}}); do
            OUTPUT=$(bin/benchmark_native_mp {{.SATS}} {{.STEP}} $W 2>&1)
            THROUGHPUT=$(echo "$OUTPUT" | grep "Throughput:" | awk '{print $2}')
            WALL_TIME=$(echo "$OUTPUT" | grep "Wall time:" | awk '{print $3}' | tr -d 's')

            if [ "$W" -eq 1 ]; then
              BASELINE=$THROUGHPUT
            fi

            # Calculate speedup (integer math with 2 decimal places)
            if [ "$BASELINE" -gt 0 ]; then
              SPEEDUP=$(awk "BEGIN {printf \"%.2f\", $THROUGHPUT / $BASELINE}")
            else
              SPEEDUP="1.00"
            fi

            printf "%7d | %18s | %13s | %6sx\n" "$W" "$THROUGHPUT" "$WALL_TIME" "$SPEEDUP"

            # Track best
            if [ "$THROUGHPUT" -gt "$BEST_THROUGHPUT" ]; then
              BEST_THROUGHPUT=$THROUGHPUT
              BEST_WORKERS=$W
            fi
          done

          echo ""
          echo "=== Optimal: WORKERS=$BEST_WORKERS ($BEST_THROUGHPUT prop/s) ==="

  native:build:batch:
    desc: Compile the SIMD batch SGP4 benchmark
    vars:
      PWD:
        sh: pwd
    cmds:
      - cmd: |
          mkdir -p bin
          echo "Compiling SIMD batch benchmark..."
          cc -O3 -march=native -o bin/benchmark_native_batch src/benchmark_native_batch.c -lm
          echo "Built: bin/benchmark_native_batch"

  native:benchmark:batch:
    desc: Run SIMD batch SGP4 benchmark. Args SATS=9534 STEP=60 WORKERS=1
    deps:
      - native:build:batch
    vars:
      SATS: '{{.SATS | default "9534"}}'
      STEP: '{{.STEP | default "60"}}'
      WORKERS: '{{.WORKERS | default "1"}}'
    cmds:
      - bin/benchmark_native_batch {{.SATS}} {{.STEP}} {{.WORKERS}}

  native:benchmark:compare:
    desc: Compare CSPICE vs SIMD batch performance
    deps:
      - native:build:parallel
      - native:build:batch
    vars:
      SATS: '{{.SATS | default "9534"}}'
      STEP: '{{.STEP | default "60"}}'
      WORKERS: '{{.WORKERS | default "12"}}'
      KERNELS_DIR: '{{.PWD}}/.cspice/kernels'
      PWD:
        sh: pwd
    env:
      SPICE_KERNELS: '{{.KERNELS_DIR}}'
    cmds:
      - cmd: |
          echo "=== Performance Comparison (SATS={{.SATS}}, STEP={{.STEP}}, WORKERS={{.WORKERS}}) ==="
          echo ""
          echo "--- CSPICE (fork) ---"
          bin/benchmark_native_mp {{.SATS}} {{.STEP}} {{.WORKERS}}
          echo ""
          echo "--- SIMD Batch ---"
          bin/benchmark_native_batch {{.SATS}} {{.STEP}} {{.WORKERS}}

  native:clean:
    desc: Remove native CSPICE installation and binaries
    cmds:
      - rm -rf .cspice bin
      - echo "Removed .cspice and bin directories"

  # ==========================================================================
  # Native Addon Tasks (Node.js N-API with SIMD)
  # ==========================================================================

  native:addon:build:
    desc: Build native SGP4 addon for current platform
    cmds:
      - cmd: |
          echo "Installing node-addon-api..."
          npm install --save-dev node-addon-api node-gyp

          echo "Building native addon..."
          cd src/native-addon
          npx node-gyp configure
          npx node-gyp build

          echo "Moving addon to build directory..."
          mkdir -p ../../build/Release
          cp build/Release/sgp4_native.node ../../build/Release/

          echo "Built: build/Release/sgp4_native.node"

  native:addon:server:
    desc: Run native addon server on host (port 50001)
    deps:
      - native:addon:build
    cmds:
      - npx tsx lib/server-native.ts
    env:
      NATIVE_PORT: "50001"

  container:build:native:
    desc: Build native addon container image
    cmds:
      - "{{.CONTAINER_BIN}} compose -f {{.COMPOSE_FILE}} --profile native build spice-api-native"

  container:start:native:
    desc: Start native addon server in Docker (port 50001)
    cmds:
      - "GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo '-') {{.CONTAINER_BIN}} compose -f {{.COMPOSE_FILE}} --profile native up -d spice-api-native"
      - echo "Waiting for server to start..."
      - sleep 3
      - echo ""
      - echo "Native server running at http://localhost:50001"
      - echo "  task container:logs:native  - View logs"
      - echo "  task container:stop:native  - Stop server"

  container:stop:native:
    desc: Stop native addon server container
    cmds:
      - "{{.CONTAINER_BIN}} compose -f {{.COMPOSE_FILE}} --profile native stop spice-api-native"
      - "{{.CONTAINER_BIN}} compose -f {{.COMPOSE_FILE}} --profile native rm -f spice-api-native"

  container:logs:native:
    desc: View logs from native addon server
    cmds:
      - "{{.CONTAINER_BIN}} compose -f {{.COMPOSE_FILE}} --profile native logs spice-api-native {{.CLI_ARGS}}"

  container:start:both:
    desc: Start both WASM (50000) and Native (50001) servers
    cmds:
      - "GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo '-') {{.CONTAINER_BIN}} compose -f {{.COMPOSE_FILE}} --profile native up -d"
      - echo "Waiting for servers to start..."
      - sleep 5
      - echo ""
      - 'echo "WASM server:   http://localhost:50000"'
      - 'echo "Native server: http://localhost:50001"'

  container:stop:both:
    desc: Stop both WASM and Native servers
    cmds:
      - "{{.CONTAINER_BIN}} compose -f {{.COMPOSE_FILE}} --profile native down -v"

  test:api:compare:
    desc: Compare WASM vs Native API performance
    cmds:
      - cmd: |
          echo "=== Performance Comparison ==="
          echo ""
          echo "--- WASM Server (port 50000) ---"
          task test:api:propagate:tle:t0:tf:txt:parallel SERVICE_HOST_PORT=50000
          echo ""
          echo "--- Native Server (port 50001) ---"
          task test:api:propagate:tle:t0:tf:txt:parallel SERVICE_HOST_PORT=50001

  benchmark:all:
    desc: Run all benchmarks (Docker HTTP + Host Native). Args SATS=9534 PARALLEL=14 WORKERS=14
    silent: true
    deps:
      - task: container:start:both
        silent: true
      - task: native:build:batch
        silent: true
      - task: native:build:parallel
        silent: true
    vars:
      SATS: '{{.SATS | default "9534"}}'
      PARALLEL: '{{.PARALLEL | default "14"}}'
      WORKERS: '{{.WORKERS | default "14"}}'
    cmds:
      - cmd: |
          echo "╔══════════════════════════════════════════════════════════════════╗"
          echo "║              COMPREHENSIVE SGP4 BENCHMARK SUITE                  ║"
          echo "╠══════════════════════════════════════════════════════════════════╣"
          echo "║  SATS={{.SATS}}  PARALLEL={{.PARALLEL}}  WORKERS={{.WORKERS}}                          ║"
          echo "╚══════════════════════════════════════════════════════════════════╝"
          echo ""
      - cmd: |
          echo "┌──────────────────────────────────────────────────────────────────┐"
          echo "│  1/4  Docker WASM Server (port 50000)                            │"
          echo "│       HTTP + Express + WASM Worker Pool                          │"
          echo "└──────────────────────────────────────────────────────────────────┘"
          task test:api:propagate:tle:t0:tf:txt:parallel SERVICE_HOST_PORT=50000 SATS={{.SATS}} PARALLEL={{.PARALLEL}}
          echo ""
      - cmd: |
          echo "┌──────────────────────────────────────────────────────────────────┐"
          echo "│  2/4  Docker Native Server (port 50001)                          │"
          echo "│       HTTP + Express + Native SIMD Worker Pool                   │"
          echo "└──────────────────────────────────────────────────────────────────┘"
          task test:api:propagate:tle:t0:tf:txt:parallel SERVICE_HOST_PORT=50001 SATS={{.SATS}} PARALLEL={{.PARALLEL}}
          echo ""
      - cmd: |
          echo "┌──────────────────────────────────────────────────────────────────┐"
          echo "│  3/4  Host Native SIMD Batch (no HTTP)                           │"
          echo "│       Raw C + SIMD vectorized propagation                        │"
          echo "└──────────────────────────────────────────────────────────────────┘"
          task native:benchmark:batch SATS={{.SATS}} WORKERS={{.WORKERS}}
          echo ""
      - cmd: |
          echo "┌──────────────────────────────────────────────────────────────────┐"
          echo "│  4/4  Host Native CSPICE Parallel (no HTTP)                      │"
          echo "│       Raw C + CSPICE + fork() parallelism                        │"
          echo "└──────────────────────────────────────────────────────────────────┘"
          task native:benchmark:parallel SATS={{.SATS}} WORKERS={{.WORKERS}}
          echo ""
      - cmd: |
          echo "╔══════════════════════════════════════════════════════════════════╗"
          echo "║                      BENCHMARK COMPLETE                          ║"
          echo "╚══════════════════════════════════════════════════════════════════╝"

  container:test:api:
    desc: Start server, run all API tests, then stop
    cmds:
      - task: container:start
      - task: test:api:all
      - task: container:stop

  # ==========================================================================
  # Cleanup Tasks
  # ==========================================================================

  container:rmi:
    desc: Remove the container image
    cmds:
      - "{{.CONTAINER_BIN}} rmi {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} || true"

  container:expunge:
    desc: Stop all containers and remove all images related to this repo
    deps:
      - container:stop
    cmds:
      - |
        echo "Stopping containers..."
        {{.CONTAINER_BIN}} stop {{.CONTAINER_NAME}} {{.CONTAINER_NAME_TEST}} 2>/dev/null || true

        echo "Removing containers and volumes..."
        {{.CONTAINER_BIN}} rm -v {{.CONTAINER_NAME}} {{.CONTAINER_NAME_TEST}} 2>/dev/null || true

        echo "Removing image {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}}..."
        {{.CONTAINER_BIN}} rmi {{.CONTAINER_IMAGE}}:{{.CONTAINER_TAG}} 2>/dev/null || true

        echo "Pruning dangling images, volumes, and networks..."
        {{.CONTAINER_BIN}} image prune -f
        {{.CONTAINER_BIN}} volume prune -f
        {{.CONTAINER_BIN}} network prune -f

        echo "Done."
